name: Dev Branch Deployment Yaml file

on:
    push:
        branches:
            - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.client_name }}

    steps:
      - name: Checkout selected repo at tag
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ github.ref_name }}  # Uses the tag from the event
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Deploying client: ${{ inputs.client_id }}"
            cd test_repo/
            git fetch --tags
            git checkout ${{ github.ref_name }}
            ls -ltr
